### ISSUE TITLE
Release first version using rultor

### ISSUE THREAD

**Issue by ashtonhogan** [ashtonhogan/tacinga#1]

**Comment by ashtonhogan** [comment]
@rultor release, tag=0.0.1

**Comment by ashtonhogan** [comment]
@yegor256 Please help

**Comment by ashtonhogan** [comment]
@rultor release, tag=0.0.1

**Comment by ashtonhogan** [comment]
@yegor256 please help

**Comment by yegor256** [comment]
@ashtonhogan read the documentation: http://doc.rultor.com/basics.html#release You have to enclose the tag is backticks

**Comment by ashtonhogan** [comment]
@rultor release, tag=`0.0.1`

**Comment by ashtonhogan** [comment]
@rultor release, tag=`0.0.1`

**Comment by ashtonhogan** [comment]
@yegor256 I read that link a few times and also looked at some of your issues, it appears that the command is issued in more than one way.

This should be working now. The build was successful but it's still saying it failed even though no errors are shown?

I suspect it may be related to https://github.com/teamed/qulice/issues/871

**Comment by yegor256** [comment]
@ashtonhogan it fails:

```
nothing to commit, working tree clean
```

This is an error message from git

**Comment by ashtonhogan** [comment]
@rultor release, tag=`0.0.1`

**Comment by ashtonhogan** [comment]
@yegor256 I just removed the `commit` line from the `.rultor` release script section. I don't really understand what process is taking place there. It seems to progress further now.

This error is now talking about the `settings.xml` which I copied from:

http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html
